/*
Creator: Andy Jara M.
*/

CREATE PROC [dbo].[PA_CALCULOUF]
(
@MES INT,
@ANNO INT,
@VARIPC DECIMAL(4,2)
)
AS
DECLARE @VALORULTUF DECIMAL(30,20)
DECLARE @NRODIAS INT
DECLARE @FACTOR DECIMAL(30,20)
DECLARE @FECHAINI DATETIME
DECLARE @FECHATER DATETIME
DECLARE @VALORUFDIA DECIMAL(30,20)
DECLARE @CONTADOR INT
DECLARE @FECHAACTUAL DATETIME

DECLARE @FACTOR1 DECIMAL(30,20)
DECLARE @FACTOR2 DECIMAL(30,20)


SET @FECHAINI = CONVERT(DATETIME, '09/' + LTRIM(RTRIM(STR(@MES))) + '/' + LTRIM(RTRIM(STR(@ANNO))), 103);
SET @FECHATER = DATEADD(MONTH, 1, @FECHAINI);
SET @FECHATER = CONVERT(DATETIME, '09' + '/' + SUBSTRING(CONVERT(VARCHAR(10), @FECHATER, 103), 4,8), 103)

SET @NRODIAS = DATEDIFF(DAY, @FECHAINI, @FECHATER);

IF EXISTS(SELECT * FROM TBLIPC WHERE MES = @MES AND ANNO = @ANNO)
BEGIN
	RAISERROR ('El año/mes seleccionado ya ha sido procesado. Operacion Cancelada.', -- Message text.
               16, -- Severity.
               1 -- State.
               );
	RETURN 99;
END
ELSE
BEGIN
	INSERT INTO TBLIPC (MES, ANNO, VARIACIONIPC) VALUES (@MES, @ANNO, @VARIPC)
END


SELECT @VALORULTUF = VALORUF FROM TBLUF WHERE 
				FECHAUF = @FECHAINI

SET @CONTADOR = 1
SET @FECHAACTUAL = DATEADD(DAY, 1, @FECHAINI);

WHILE (@CONTADOR<=@NRODIAS)
BEGIN
	SET @FACTOR1 = 1 + (@VARIPC/(CAST (100 AS DECIMAL(30,20))));
	SET @FACTOR2 = (CAST (1 AS DECIMAL(30,20)))/( CAST(@NRODIAS AS DECIMAL(30,20)))

	SET @FACTOR = POWER(@FACTOR1, @FACTOR2)
	SET @VALORUFDIA = @VALORULTUF * @FACTOR;

	print @factor1
	print @factor2
	print @factor

	INSERT INTO TBLUF (FECHAUF, VALORUF) VALUES (@FECHAACTUAL, CAST(@VALORUFDIA AS DECIMAL(10,2)))

	--SELECT @FECHAACTUAL, CAST(@VALORUFDIA AS DECIMAL(10,2))

	SET @FECHAACTUAL = DATEADD(DAY, 1, @FECHAACTUAL);
	SET @CONTADOR = @CONTADOR + 1;
	SET @VALORULTUF = @VALORUFDIA;
END


SELECT FECHAUF = CONVERT(VARCHAR(10), FECHAUF, 103), VALORUF 
FROM TBLUF WHERE FECHAUF BETWEEN DATEADD(DAY, 1, @FECHAINI) AND @FECHATER



